# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Indraw.gy Build 🖊

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: ./Frontend/package-lock.json
    - run: npm ci
      working-directory: ./Frontend
    - run: npm run build --if-present
      working-directory: ./Frontend
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
      # Artifact name
        name: dist
        # A file, directory or wildcard pattern that describes what to upload
        path: ./Frontend/dist
        # The desired behavior if no files are found using the provided path.
